# version: '3.8'
# services:
#   telegram-bot:
#     build: .
#     restart: always
#     environment:
#       TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
#       OPENAI_API_KEY: ${OPENAI_API_KEY}
#       OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
#       ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
#     volumes:
#       - ./:/app

version: '3.8'
services:
  telegram-bot:
    build: .
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
      ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
      # Add Redis connection details
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"   # Optional: expose port if you need external access
    volumes:
      - redis-data:/data

volumes:
  redis-data:
