version: '3.8'
services:
  telegram-bot:
    build: .
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
      ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
    volumes:
      - ./:/app
